### ISSUE TITLE
shape="flat" not working

### ISSUE THREAD

**Issue by skmorgane** [weecology/portalr#218]
in abundance() shape="flat" is throwing an error.

Code:
rodent_controls = abundance(".", shape="flat")

Error:
Error: Column `output` not found in `.data`
Call `rlang::last_error()` to see a backtrace 

last_error() gives:
<error>
message: Column `output` not found in `.data`
class:   `rlang_error_data_pronoun_not_found`
backtrace:
  1. portalr::abundance(".", shape = "flat")
 29. rlang:::abort_data_pronoun(x)

**Comment by ha0ye** [comment]
Hrm, will take a look.

**Comment by ha0ye** [comment]
What version of `portalr` are you running? This sounds similar to the issue that Ethan had, but which is now fixed:
https://github.com/weecology/portalr/issues/212

**Comment by skmorgane** [comment]
I checked my version and it is 0.2.6 and when I run:
data = abundance(".", shape="flat")

I still get:
Error: Column `output` not found in `.data`
Call `rlang::last_error()` to see a backtrace

I'm on my laptop now (the original problem occurred on my desktop, so maybe it's different issues but this is as far as I can go right now.

**Comment by ha0ye** [comment]
I think 0.2.7 has the bug fix. (The readme text is slightly out of date.)

**Comment by skmorgane** [comment]
Ok thanks. When I get a chance I’ll load from master and see what happens.

**Comment by skmorgane** [comment]
That did it. Thanks for the help. I'm closing the issue.
